### ISSUE TITLE
SaveScreen / RestoreScreen

### ISSUE THREAD

**Issue by jkulwicki** [rickparrish/RMLib#3]
Rick, 

Great job on this library, I love using it! 

Is there a way to save the screen and send it to the socket using SaveScreen and RestoreScreen or is it only for local stuff using Crt?

Thank you.

**Comment by rickparrish** [comment]
It's been a long time since I worked on it, so I'm not sure.  But if the method is in the Crt class then it's local only, whereas if it's in the Door class then it should work for door games.

**Comment by jkulwicki** [comment]
Well it's a great product. And thanks for making it. I'm having a blast
with it.
